### ISSUE TITLE
mongodb file

### ISSUE THREAD

**Issue by Nick-Mul** [willfinnigan/RetroBioCat#6]
Hi Will, 

I was wondering if in biocatdb_to_db.py line #11 the file name should be the "trial_activity_data" to match those at https://figshare.com/articles/software/RetroBioCat_database_files/12696482 ?

i.e. 
#EXCEL_PATH = str(Path(__file__).parents[2]) + '/data/substrate_specificity/biocatdb_2.xlsx'
EXCEL_PATH = str(Path(__file__).parents[2]) + '/data/substrate_specificity/trial_activity_data.xlsx'

**Comment by willfinnigan** [comment]
Hi Nick,

There was an issue with the column naming of the trial activity data.  I've fixed this on figshare now, and this new version should work fine for initialising the database.  Apologies for missing this - I don't initialise the database very often and recently have just been doing this from a mongodb dump file.

That default path is a bit of a relic from when the database was literally an excel sheet.  When trial_activity_data.xlsx is uploaded via the website the path to that file is used, so the filename can be anything.

Kind regards,
Will
