### ISSUE TITLE
When initializing the database, the mongo_dump.gz and Sequences files were not found

### ISSUE THREAD

**Issue by HanMengying** [willfinnigan/RetroBioCat#7]
[https://figshare.com/articles/software/RetroBioCat_database_files/12696482](url)

![QQ图片20210730175653](https://user-images.githubusercontent.com/50348328/127636834-b8b1fd1d-f67e-416b-8ce9-368ea53a0efd.png)

![QQ图片20210730175729](https://user-images.githubusercontent.com/50348328/127636880-565a3e4e-1f87-4651-ac21-ab2017adc926.png)

When I got to the step of initializing the database, the web page suggested that 4 files were needed, but I only found 3 on your website, and the mongo_dump.gz and Sequences files are missing.
After I successfully uploaded rxns_yaml.yaml and trial_activity_data.xlsx, I run the website and use the Network explorer tool, but an error is reported and no information is displayed in the background. Is it the lack of data? Or something else, how can I make this website work?

![QQ图片20210730175754](https://user-images.githubusercontent.com/50348328/127636889-2502a101-e634-4331-9bf0-10e5b1898774.png)

**Comment by willfinnigan** [comment]
Hi HanMengying,

The mongo_dump.gz is an alternative method of creating the database from a backup.  I have updated the readme to mention this.  If you do not have a mongo_dump.gz file then ignore this option.

Unfortunetly we're also not able to provide a sequences file at the moment, but this is not strictly necessary for the retrosynthesis elements of the website to work.

So ensure that you've uploaded the reactions yaml and the activity data (in the BioCatDB excel field).  If these are loaded correctly, and you have a worker process running, network explorer should work.

To debug why you're getting an error, you'll need to look at the terminal output to see where the error is.  Feel free to post that here and I can try and help you.  

However I would recommend using the hosted version of retrobiocat at https://retrobiocat.com 

Kind regards,
Will
