### ISSUE TITLE
clarifying the fields in rules file 

### ISSUE THREAD

**Issue by kkatsano** [willfinnigan/RetroBioCat#8]
Hi Will,

Thank you very much for your effort. Retrobiocat is a handy software that has proven to be useful in computer aided biocatalysis planning. 
I looked at the data you shared and was just wondering if you could provide additional information about some fields in the rxn_yaml.yaml. Would you be able to tell please what positive_tests and negative_tests mean in the reactions and why they are included? Also, there are fields "Two_step" and "experimental" which I struggle to understand as well. Could you please tell what they mean?

Best,
Ksenia

**Comment by willfinnigan** [comment]
Hi Ksenia,

The positive and negative tests are used when making the rules to ensure they behave as expected.  Basically positive tests are products which should return substrates when the rule is applied.  Negative are the opposite.

Experimental is just a flag to turn off rules which we are still working on, but they can be switched on in the options pop-up of the site.

Two step rules are a more recent addition - I don't think these are used in the older version of the code we have in this public repo.  But basically some reactions are just the application of two existing rules one after another (for example Reductive amination is imine formation followed by imine reduction.). I was struggling to get the correct chirality with a single smarts for reductive amination - but a two step method works nicely.  The use of these rules can also be turned on or off in the options.
